# Generated by Django 5.1.6 on 2025-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'In Game')], default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('role', models.SmallIntegerField(choices=[(2, 'Outcast'), (1, 'Admin'), (0, 'Student')], default=0)),
            ],
        ),
    ]
