# Generated by Django 5.1.5 on 2025-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(2, 'Outcast'), (0, 'Student'), (1, 'Admin')], default=0),
        ),
    ]
