# Generated by Django 5.1.5 on 2025-02-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(2, 'Outcast'), (1, 'Admin'), (0, 'Student')], default=0),
        ),
    ]
