# Generated by Django 5.1.5 on 2025-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(2, 'Outcast'), (0, 'Student'), (1, 'Admin')], default=0),
        ),
    ]
