# Generated by Django 5.1.5 on 2025-02-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0023_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_one_score', models.BigIntegerField(default=0)),
                ('player_two_score', models.BigIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_player_one', to='users.user')),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_player_two', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TourRound',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_num', models.BigIntegerField(default=1)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TourMatch',
            fields=[
                ('tour_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tourround')),
            ],
        ),
    ]
