# Generated by Django 5.1.5 on 2025-02-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_ai_opponent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
