FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt .

COPY . .

RUN pip install --upgrade pip 

RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8000

# RUN django-admin startproject backend .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]