FROM python:3

WORKDIR /usr/src/app

RUN apt-get update -y
RUN apt-get install -y --no-install-recommends nano

RUN pip install --no-cache-dir django gunicorn psycopg2-binary djangorestframework

RUN django-admin startproject backend .
RUN python manage.py startapp api

# COPY settings.py backend/settings.py

# CMD ["./manage.py", "runserver", "0.0.0.0:8000"]
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi"]
# CMD ["tail", "-f"]