# Generated by Django 5.1.6 on 2025-02-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=500)),
                ('receiver', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='users.user')),
                ('sender', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='users.user')),
            ],
        ),
    ]
