# Generated by Django 5.1.6 on 2025-02-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentBy', models.IntegerField(default=0)),
                ('friend_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Inactive')], default='0', max_length=10)),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='users.user')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['friend1', 'friend2'], name='friends_fri_friend1_65a995_idx')],
                'unique_together': {('friend1', 'friend2')},
            },
        ),
    ]
